# Generated by Django 4.1.2 on 2022-10-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
