# Generated by Django 4.1.2 on 2022-10-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_shopcart_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopcart',
            options={'managed': True, 'verbose_name': 'Shopcart', 'verbose_name_plural': 'Shopcarts'},
        ),
        migrations.AlterModelTable(
            name='shopcart',
            table='shopcart',
        ),
    ]
