# Generated by Django 4.1.2 on 2022-10-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shopcart',
        ),
    ]
