# Generated by Django 4.1.2 on 2022-10-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imgr',
            field=models.ImageField(default='prouct.jpg', upload_to='Product'),
        ),
    ]
